---
title: "Chris Talbot | CV"
subtitle: "Ph.D. Student in Computational Biology, Cornell University | National Science Foundation Graduate Research Fellow"
format:
  html:
    toc: true
    toc-depth: 2
    toc-expand: 2
    other-links:
      - text: "PDF"
        href: "files/CV.pdf" # Make sure this path is correct and the PDF is updated
css: cv.css
---

**Status**: Ph.D. Student in Computational Biology at Cornell University, Messer Lab <br> **Fields**: Population Genetics, Computational Biology, Evolutionary Ecology <br> **Interests**: Population genetics, global change, stochastic modeling, conservation <br> **Techs**: Python, R, C++, Rust, TypeScript, SLiM

## Summary

-   First-gen academic and biologist with years of experience in lab, field, and computational work.
-   Interested in patterns and drivers of ecological organization across spatiotemporal scales under global change.
-   Exploring emerging methods for complex systems, including community science and machine learning.

## Education

**Ph.D.** -- Computational Biology [2025-Present]{.cvdate} <br> *Cornell University* <br>

-   Advisor: Philipp Messer
-   Key Funding: National Science Foundation Graduate Research Fellowship Program (2025-2030)

**B.S.** -- Ecology, Evolution, and Biodiversity [2024]{.cvdate} <br> *University of Michigan (UMich)* [GPA: 3.74]{.cvgpa} <br>

-   Graduated with **Highest Honors** under the supervision of Marjorie Weber
-   Honors Thesis: [Patterns of floral color in communities of common Northeast American wildflowers](files/honors_thesis.pdf) <!-- Assuming you have this PDF -->
-   Coursework: Statistics & probability, programming & data structures, genetics, macroevolution, ethnobotany

**A.G.S.** -- General Studies (Computer Science & Mathematics Concentration) [2020]{.cvdate} <br> *Grand Rapids Community College (GRCC)* [GPA: 3.9]{.cvgpa} <br>

-   Coursework: C++ programming, database development, web application programming, information security

## Research

**Doctoral Researcher** -- Messer Lab [2025-Present]{.cvdate} <br> *Cornell University - Computational Biology* <br>

**Research Programmer** -- Bradburd Lab [2024-2025]{.cvdate} <br> *UMich-Ecology & Evolutionary Biology (EEB)* <br>

-   Project: Testing, documenting, and visualizing novel geographic evolutionary inference methods

**Lab Technician** -- Weber Lab [2022-2025]{.cvdate} <br> *UMich-EEB* <br>

-   Project: "Patterns of floral color in communities of common Northeast American wildflowers"

**Undergraduate Researcher** -- Márquez Lab [2021-2022]{.cvdate} <br> *UMich-EEB* <br>

-   Project: "Optimizing CRISPR-Cas9 genetic modification in *Phyllobates* poison-dart frogs"

## Publications

#### *Published:*

**2025** -- Graham, C. D. K., ..., [Talbot, C. A.]{.underline}, Yerks, A. L., & Weber, M. G. Mite domatia and associated mite density in a North American Eastern Deciduous Forest in Michigan. **Published in Ecology and Evolution.**

#### *Pre-prints/In Review:*

**2025** -- [Talbot, C. A.]{.underline}, Bradburd, G. S. ARGscape: A modular, interactive tool for manipulation of spatiotemporal ancestral recombination graphs. arXiv:2510.07255 \[q-bio.PE\]. **Submitted to Bioinformatics.**

**2025** -- [Talbot, C. A.]{.underline}, Weber, M. G. Opposing seasonal dynamics in phylogenetic and flower color diversity of co-flowering wildflower assemblages. bioRxiv 2025.10.21.683724. **Submitted to Ecology.**

#### *In Prep:*

**2025** -- [Talbot, C. A.]{.underline}, Bradburd, G. S. Optimizing temporal sampling strategies for spatial population genetic inference using ancestral recombination graphs. **In Preparation for Genetics.**

## Software Development

**Open-Source Contributor** [2025-Present]{.cvdate} <br> *SLiM simulator, Messer Lab, Cornell University* <br>

**Primary Developer** [2025-Present]{.cvdate} <br> *ARGscape software* <br>

## Funding

**Total: \$174,280**

**Graduate Research Fellowship Program** [2025-2030]{.cvdate} <br> *National Science Foundation* [\$159,000]{.cvgpa} <br>

**Graduate School Dean's Scholar Fellowship** [2025]{.cvdate} <br> *Cornell University* [\$2,000]{.cvgpa} <br>

**Chancellor's Fellowship** [Offered 2025]{.cvdate} <br> *University of California, Berkeley* [(Declined)]{.cvgpa} <br>

**Eugene Cota-Robles Fellowship** [Offered 2025]{.cvdate} <br> *University of California, Davis* [(Declined)]{.cvgpa} <br>

**Eugene Cota-Robles Fellowship** [Offered 2025]{.cvdate} <br> *University of California, Santa Cruz* [(Declined)]{.cvgpa} <br>

**Biological Station Student Fellowship** [2023]{.cvdate} <br> *UMich Biological Station* [\$1,680]{.cvgpa} <br>

**Student Research Grant** [2022-2023]{.cvdate} <br> *UMich Undergraduate Research Opportunity Program (UROP)* [\$5,000]{.cvgpa} <br>

**Travel Grant** [2022]{.cvdate} <br> *SACNAS* [\$2,500]{.cvgpa} <br>

**Biomedical & Life Sciences Summer Fellowship** [2022]{.cvdate} <br> *UMich UROP* [\$4,000]{.cvgpa} <br>

**Community College Summer Institute Fellowship** [2019]{.cvdate} <br> *UMich-School of Information* [\$100]{.cvgpa} <br>

## Teaching & Mentoring

**Docent (Volunteer Educator)** [2023-Present]{.cvdate} <br> *Matthaei Botanical Gardens & Nichols Arboretum* <br>

**Test Writer & Proctor, Forestry & Botany (Volunteer)** [2023-2025]{.cvdate} <br> *UMich Science Olympiad* <br>

**Director of Percussion** [2022-2023]{.cvdate} <br> *Lake Orion Community Schools, Lake Orion, MI* <br>

**Transfer Student Peer Mentor** [2022-2023]{.cvdate} <br> *UMich-LSA Transfer Bridges Program* <br>

**Director of Percussion** [2019-2022]{.cvdate} <br> *Spring Lake Public Schools, Spring Lake, MI* <br>

**Freelance Percussion Instructor & Composer** [2018-2022]{.cvdate} <br> *8 school districts across Michigan* <br>

**Professional Peer Tutor** -- Mathematics, Language Arts [2019-2020]{.cvdate} <br> *GRCC Drop-in Tutoring Labs* <br>

## Invited Talks & Workshops

**2025** — tskit-dev Seminar [Virtual (Invited Talk)]{.small}

**Upcoming 2025** — ARGEvol Conference [Porto, Portugal (Invited Talk)]{.small}

**Upcoming 2025** — ARGEvol Spatial ARG Workshop [Porto, Portugal (Workshop Contributor)]{.small}

## Contributed Talks

**Third Joint Congress on Evolutionary Biology** [Montreal, QC (Talk)]{.small} [2024]{.cvdate} <br> [*Do flowers of a color bloom together? (Talk V.2)*](files/evolution_talk.pdf)

**Botany 2024** [Grand Rapids, MI (Lightning Talk)]{.small} [2024]{.cvdate} <br> [*Do flowers of a color bloom together? (Lightning Talk)*](files/botany_talk.pdf)

**UMich Ecology & Evolutionary Biology** [Ann Arbor, MI (Honors Thesis Defense)]{.small} [2024]{.cvdate}

## Posters

**Third Joint Congress on Evolutionary Biology** [Montreal, QC]{.small} [2024]{.cvdate} <br> [*Do flowers of a color bloom together? (Poster V.2)*](evolution2024poster.html) <!-- Link from old CV -->

**Botany 2024** [Grand Rapids, MI]{.small} [2024]{.cvdate} <br> [*Do flowers of a color bloom together? (Poster V.1)*](botany2024poster.html) <!-- Link from old CV -->

**UMich Undergraduate Research Opportunity Program Symposium** [Ann Arbor, MI]{.small} [2022]{.cvdate} <br> [*Optimizing CRISPR-Cas9 genetic modification in* Phyllobates\* poison-dart frogs\*](files/pres/poster_22apr22.pdf) <!-- Link from old CV -->

## Professional & Service

**Percussionist** [2024-2025]{.cvdate} <br> *Straits of Mackinac Concert Band, Mackinaw City, MI* <br>

**Co-Founder, President, and Volunteer** [2023-2025]{.cvdate} <br> *Students for Public Power @UM* <br>

**Shift Leader** [2021-2023]{.cvdate} <br> *Biggby Coffee, Grand Rapids, MI* <br>

**Seasonal Retail Lead** [2019]{.cvdate} <br> *John Ball Zoo, Grand Rapids, MI* <br>

## Languages

**R**: Advanced (C1) <br> **German**: Intermediate (B2) <br> **C++**: Intermediate (B2) <br> **Python**: Intermediate (B2) <br> **TypeScript**: Intermediate (B1) <br> **Nishnaabemwin (Eastern Ojibwe)**: Beginner (A1) <br>

## Certifications

**Certified Michigan Naturalist** [2024]{.cvdate} <br> *Michigan State University Extension* <br>

## Professional Memberships

**American Society of Naturalists** -- *Student Member* [2024-Present]{.cvdate}

**Society for the Study of Evolution** -- *Student Member* [2022-Present]{.cvdate}

**Botanical Society of America** -- *Student Member* [2024-2025]{.cvdate}

## Extracurriculars

**Founding Member** [2023-2025]{.cvdate} <br> *UMich Ecological Restoration Club* <br>

**Vice President** [2019-2020]{.cvdate} <br> *GRCC Programmers* <br>

**Ensemble & Section Leader, Performer** [2014-2020]{.cvdate} <br> *Genesis Percussion Ensemble* <br>